### ISSUE TITLE
Parser exception handling

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#11]
Parsing can throw different kinds of exceptions. It would be nice if it would always throw `IllegalArgumentException`

eg:
parsing `* *[triple space here]* * ?` throws a NumberFormatException with message `For input string: ""`

```java
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.cronutils.model.field.constraint.FieldConstraints.stringToInt(FieldConstraints.java:70)
	at com.cronutils.model.field.On.<init>(On.java:28)
	at com.cronutils.parser.field.FieldParser.parse(FieldParser.java:46)
	at com.cronutils.parser.field.CronParserField.parse(CronParserField.java:68)
	at com.cronutils.parser.CronParser.parse(CronParser.java:86)
```

**Comment by jmrozanec** [comment]
Thank you for reporting this! After some looking at crontab documentation and stackoverflow, I found this is a bug. Multiple spaces should be ignored. I am fixing this soon.

Reference: [do spaces matter in a crontab?](http://unix.stackexchange.com/questions/157558/do-spaces-matter-in-a-crontab)

**Comment by jmrozanec** [comment]
Solved with commit 161c63716345d9f1070cdd435d03575989fc5917

**Comment by francisdb** [comment]
You might want to document in the parse method javadoc what exceptions can be expected...

**Comment by jmrozanec** [comment]
@francisdb Done! Thanks for the suggestion. You are welcome to contribute enhancing current documentation / jdocs of the project.

**Comment by francisdb** [comment]
I'm still getting NumberFormatExceptions

try this `* * * * $ ?`

So the docs should be updated or they should not be thrown

**Comment by jmrozanec** [comment]
@francisdb Yes, you were right. I updated the exceptions thrown, to IllegalArgumentException and added some more validations in order to prevent this and similar cases.

**Comment by francisdb** [comment]
Great. Thanks!
